### PR TITLE
Set DOTNET_ASSEMBLY_NAME to be able to use samples/MusicStore as context-dir

### PR DESCRIPTION
**Pull request by tmds**
Requires https://github.com/redhat-developer/s2i-dotnetcore/pull/42

### CODE REVIEW

**Comment by jerboaa** [comment]
Why are we not setting `name` or `buildOptions/outputName` in `project.json`? If upstream is not doing it (yet), we should perhaps try to get it merged upstream as well.

**Comment by tmds** [comment]
> Why are we not setting name or buildOptions/outputName in project.json? If upstream is not doing it (yet), we should perhaps try to get it merged upstream as well.

Setting name or buildOptions/outputName isn't a common practice. Setting it here would not fix anything.

**Comment by jerboaa** [comment]
If the music store app expects the assembly to be `MusicStore`, it would make sense to set it in project.json. Maybe that's just me. Why would setting it here not fix anything? It would change the s2i build to produce `MusicStore.dll` over `src.dll`.

**Comment by jerboaa** [comment]
> Why would setting it here not fix anything?

Scratch that, If we changed it in project.json we'd need to set DOTNET_ASSEMBLY_NAME to match it anyway. Pretty ugly :( I need to ponder this a bit more...

**Comment by tmds** [comment]
> Pretty ugly :( I need to ponder this a bit more...

Tell it to the project.json guys. Msbuild fixes this.

**Comment by tmds** [comment]
@jerboaa ok to merge?

**Comment by jerboaa** [comment]
@tmds I'm not sure how to proceed with this. It would probably work, but maybe we should take this opportunity to show how to deploy this app as-is (i.e. not some subfolder of it). For example, would it be possible to massage the template to not specify the context-dir and use DOTNET_RESTORE_ROOT and DOTNET_STARTUP_PROJECT? That's what I'm pondering.

**Comment by tmds** [comment]
> @tmds I'm not sure how to proceed with this. It would probably work, but maybe we should take this opportunity to show how to deploy this app as-is (i.e. not some subfolder of it). For example, would it be possible to massage the template to not specify the context-dir and use DOTNET_RESTORE_ROOT and DOTNET_STARTUP_PROJECT? That's what I'm pondering.

Yes, that is the alternative. Since project.json will be EOL in a couple of months, I prefer to workaround the project.json limitation by setting DOTNET_ASSEMBLY_NAME. Msbuild won't need this. The template (https://github.com/redhat-developer/s2i-dotnetcore/pull/27) can then also use default values for DOTNET_STARTUP_PROJECT and DOTNET_RESTORE_ROOT and just work with context-dir, which will be familiar to s2i users.

**Comment by jerboaa** [comment]
OK, merged. Whether we are going to use this in the template is not clear to me yet. Perhaps one template could show it :)

**Pull request merged**
